const LS='itachi_supabase_config_v1';
let client=null, session=null, config=null;
const $=id=>document.getElementById(id);
function setMsg(id,msg){$(id).textContent=msg}
function loadConfig(){try{config=JSON.parse(localStorage.getItem(LS)||'null')}catch{}; if(config){$('supabaseUrl').value=config.url||'';$('supabaseKey').value=config.key||''}}
function saveConfig(){const url=$('supabaseUrl').value.trim().replace(/\/$/,'');const key=$('supabaseKey').value.trim();if(!url||!key)return setMsg('setupMsg','Enter both values.');config={url,key};localStorage.setItem(LS,JSON.stringify(config));init()}
async function init(){loadConfig();if(!config?.url||!config?.key){$('setup').classList.remove('hidden');$('login').classList.add('hidden');$('dashboard').classList.add('hidden');return}client=window.supabase.createClient(config.url,config.key);const {data}=await client.auth.getSession();session=data.session;render();if(session)loadAssets()}
function render(){const logged=!!session;$('setup').classList.add('hidden');$('login').classList.toggle('hidden',logged);$('dashboard').classList.toggle('hidden',!logged);$('logout').classList.toggle('hidden',!logged);if(!logged)setMsg('loginMsg','Sign in with your admin account.')}
async function login(){setMsg('loginMsg','Signing in…');const {data,error}=await client.auth.signInWithPassword({email:$('email').value.trim(),password:$('password').value});if(error)return setMsg('loginMsg',error.message);session=data.session;render();loadAssets()}
async function signup(){setMsg('loginMsg','Creating account…');const {error}=await client.auth.signUp({email:$('email').value.trim(),password:$('password').value});setMsg('loginMsg',error?error.message:'Account created. Check your email if confirmation is enabled, then sign in.')}
async function logout(){await client.auth.signOut();session=null;render()}
async function getSettings(){const {data,error}=await client.from('site_media').select('*').eq('id',1).maybeSingle();if(error)throw error;return data||{id:1}}
function publicUrl(path){return client.storage.from('itachi-media').getPublicUrl(path).data.publicUrl}
function show(id,type,url,title,artist){const el=$(id);el.innerHTML='';if(!url){el.innerHTML='<span class="meta">No live asset yet.</span>';return}if(type==='audio'){const a=document.createElement('audio');a.controls=true;a.src=url;el.append(a)}else if(type==='video'){const v=document.createElement('video');v.controls=true;v.muted=true;v.src=url;el.append(v)}else{const img=document.createElement('img');img.src=url;el.append(img)}const m=document.createElement('span');m.className='meta';m.textContent=[title,artist].filter(Boolean).join(' — ');el.append(m)}
async function loadAssets(){try{const s=await getSettings();show('musicCurrent','audio',s.music_url,s.music_title,s.music_artist);show('videoCurrent','video',s.hero_video_url);show('baseCurrent','image',s.base_image_url);show('sealCurrent','image',s.seal_image_url);show('sageCurrent','image',s.sage_image_url);$('status').textContent='Live configuration loaded'}catch(e){$('status').textContent=e.message}}
function fileFor(type){return ({music:$('musicFile'),video:$('videoFile'),base:$('baseFile'),seal:$('sealFile'),sage:$('sageFile')})[type].files[0]}
function ext(file){return (file.name.split('.').pop()||'bin').toLowerCase()}
async function uploadAsset(type){try{const file=fileFor(type);if(!file)return alert('Choose a file first.');$('status').textContent='Uploading…';const path=`${type}/${Date.now()}-${crypto.randomUUID()}.${ext(file)}`;const {error:upErr}=await client.storage.from('itachi-media').upload(path,file,{upsert:false,cacheControl:'3600',contentType:file.type});if(upErr)throw upErr;const url=publicUrl(path);const patch={updated_at:new Date().toISOString()};if(type==='music'){patch.music_url=url;patch.music_title=$('musicTitle').value.trim()||file.name;patch.music_artist=$('musicArtist').value.trim()}if(type==='video'){patch.hero_video_url=url;const poster=$('posterFile').files[0];if(poster){const pp=`poster/${Date.now()}-${crypto.randomUUID()}.${ext(poster)}`;const {error}=await client.storage.from('itachi-media').upload(pp,poster,{cacheControl:'3600',contentType:poster.type});if(error)throw error;patch.hero_poster_url=publicUrl(pp)}}if(type==='base')patch.base_image_url=url;if(type==='seal')patch.seal_image_url=url;if(type==='sage')patch.sage_image_url=url;const {error}=await client.from('site_media').upsert(patch,{onConflict:'id'});if(error)throw error;$('status').textContent='Published live ✓';await loadAssets()}catch(e){$('status').textContent='Error: '+e.message}}
$('saveConfig').onclick=saveConfig;$('loginBtn').onclick=login;$('signupBtn').onclick=signup;$('logout').onclick=logout;document.querySelectorAll('.upload').forEach(b=>b.onclick=()=>uploadAsset(b.dataset.type));loadConfig();init();
